apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-event-config
  namespace: kube-system
data:
  config.yaml: |
    namespaces:
      - default
    labels:
      - "app"
      - "owner"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: kube-pod-event
  name: kube-pod-event
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-pod-event
  template:
    metadata:
      labels:
        app: kube-pod-event
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: kube-pod-event
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/muco/pod-event:latest
          imagePullPolicy: "Always"
          name: kube-pod-event
          command:
            - "/pod-event"
            - "--kubeconfig=/.kube/config"
            - "--ns=default"
            - "--sink=mysql:?root:password@tcp(192.168.50.12:31112)/events?charset=utf8"
          env:
          # If TZ is assigned, set the TZ value as the time zone
          - name: TZ
            value: "Asia/Shanghai"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: zoneinfo
              mountPath: /usr/share/zoneinfo
              readOnly: true
            - name: pod-event-cm
              mountPath: /.kube/config
              subPath: config.yaml
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 250Mi
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: zoneinfo
          hostPath:
            path: /usr/share/zoneinfo
        - name: pod-event-cm
          configMap:
            name: kube-event-config